### ISSUE TITLE
Oyodo instead of Ooyodo

### ISSUE THREAD

**Issue by peterbuk** [yuyuvn/KanColleViewer#44]
This is the only version where Oyodo is used as the romaji instead of Ooyodo which is seen everywhere else. Any particular reason for this?

It's just a minor thing, but it bugs me enough that I feel compelled to change it manually myself everytime I update.

**Comment by yuyuvn** [comment]
Translation work of many people so it may have some inconsistency. If you found any of it, please let me know. Thank you.

**Comment by kazuau** [comment]
Since I'm not using the translation feature since I'm a Japanese speaker, just FYI.
 I dare say "Oyodo" is correct and "Ooyodo" is incorrect.

US Navy officialy called her "Oyodo": 
http://www.history.navy.mil/our-collections/artifacts/research-guides/us-naval-technical-mission-to-japan-reports-in-the-navy-department-library.html#ships
(Also, there are some other documents found at this site.)

Wikipedia(en) calls her "Oyodo".
http://en.wikipedia.org/wiki/Japanese_cruiser_%C5%8Cyodo

And we write down "大淀川" as Oyodo River and "大淀区" as Oyodo-ku.

Lastly, "Ooyodo" is not correct Japanese Romaji, so I'm not sure how to pronounce this notation in Japanese.

HTH,  but I think it's OK to leave it as it is if the majority of English-speaking Teitokus prefer to do so.

**Comment by peterbuk** [comment]
Yeah that's why I asked if there was a reason for this. There's often a lot of discrepancies when お/ょう gets translated into romaji it seems. But I agree, in this case Ooyodo is probably preferred because it's consistent with the English community.

**Comment by c933103** [comment]
Japanese speakers tend to use O or Ō while Western general users tend to use Ō or Oo. It is a matter of preferences.
